### ISSUE TITLE
Bug in getClosestRoadDirection

### ISSUE THREAD

**Issue by Dgleish** [teamdelta2016/TeamDelta#21]
``` java
public Direction getClosestRoadDirection() {
        double min_diff = 360;
        Direction closest = new Direction(0);
        for (Direction dir : m_road_angles) {
            double diff = Math.min(Math.abs(m_primary_direction.getDegrees() - dir.getDegrees()),
   !!!!!!!                 Math.abs(Math.abs(m_primary_direction.getDegrees() - dir.getDegrees() - 360)));
            if (diff < min_diff) {
                min_diff = diff;
                closest = dir;
            }
        }
        return closest;
    }
```

On the line denoted !!!!!!, I don't understand the use of two `Math.abs()` calls. Also, as subtraction is left-associative, this gives `(m_primary_direction.getDegrees() - dir.getDegrees)-360` whereas I would have thought `m_primary_direction.getDegrees() - (dir.getDegrees-360)` is the right order.

This could very well be me just not understanding however.

**Comment by Basha133** [comment]
Yes, the double Math.abs is redundant, and the second part is definitely a bug, however I think that just changing the order isn't correct either - I hope that the new formula is now correct, but I don't trust myself with math anymore, so see if it works please, I will make a pull request.
